# Generated by Django 3.1.7 on 2021-03-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='actual_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='offered_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
