# Generated by Django 3.1.7 on 2021-03-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210329_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radio',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='radio',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='radio',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='radio',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='text',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
