# Generated by Django 3.1.7 on 2021-03-30 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210330_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='text',
            old_name='actual_answer',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='offered_answer',
            new_name='input_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='actual_answer',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='offered_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('radio', 'Radio'), ('text', 'Text')], default='radio', max_length=31),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.AddField(
            model_name='radio',
            name='answers',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='radio_related', to='quiz.choice'),
        ),
    ]
