# Generated by Django 3.1.7 on 2021-03-31 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210331_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='answer',
            new_name='choice_option',
        ),
        migrations.RenameField(
            model_name='radio',
            old_name='answers',
            new_name='answer_options',
        ),
        migrations.AddField(
            model_name='radio',
            name='selected_answer',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='radio_selected', to='quiz.choice'),
        ),
    ]
