# Generated by Django 3.1.7 on 2021-03-31 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210331_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio',
            name='answer_options',
        ),
        migrations.AddField(
            model_name='radio',
            name='answer_option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='radio_options', to='quiz.choice'),
        ),
    ]
