# Generated by Django 3.1.7 on 2021-03-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20210331_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio',
            name='selected_answer',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
