# Generated by Django 3.1.7 on 2021-04-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210401_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='timeline',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
