# Generated by Django 3.1.7 on 2021-04-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20210401_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='timeline',
            new_name='time',
        ),
    ]
