# Generated by Django 3.1.7 on 2021-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_remove_quiz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
