# Generated by Django 3.1.7 on 2021-04-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_quiz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
